[package]
name = "terrain"
version = "0.1.0"
authors = ["Daniele D'Orazio <daniele@develer.com>"]
edition = "2018"

[dependencies]
image = "0.24"
rand = "0.8"
rand_pcg = "0.3"
simdnoise = "3.1"
structopt = "0.3"
